FROM ruby:2.4.1

ENV LC_ALL=C.UTF-8

RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get update && \
    apt-get install -y \
        mysql-client \
        nodejs \
        --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*
